/* ntt_gen_fixture.c — gcc-only generator for the cross-compiler parity fixture.
 *
 * Emits core/ntt_crt/ntt_ref_vectors.h: a set of (N, a, b, expected) cases where
 * `expected` is the negacyclic product computed by the __int128 oracle
 * (ntt_ref_negacyclic_mul). T_NTT_3 compiles this header on EVERY compiler and
 * asserts the production kernel reproduces `expected` bit-for-bit — so MSVC,
 * which cannot compile the __int128 oracle, still gates against it via these
 * pre-computed vectors (roadmap §3.7).
 *
 * Cases span coefficient magnitudes up to 2^28 so the fixture genuinely
 * exercises the ~2^60 CRT recombination + centering, not just the small-input
 * range the live tests use.
 *
 * NOT part of the CMake build (gcc + __int128 only). Regenerate with:
 *     gcc -std=c11 -I include core/ntt_crt/ntt_gen_fixture.c \
 *         core/ntt_crt/ntt_ref_int128.c core/ntt_crt/ntt_crt.c -o gen.exe
 *     ./gen.exe > core/ntt_crt/ntt_ref_vectors.h
 */
#include "sp/ntt_crt.h"
#include <stdint.h>
#include <stdio.h>

void ntt_ref_negacyclic_mul(uint32_t N, const int32_t *a, const int32_t *b,
                            int64_t *out);

static uint64_t rng_state;
static void rng_seed(uint64_t s) { rng_state = s ? s : 1u; }
static uint64_t rng_next(void) {
    uint64_t x = rng_state;
    x ^= x >> 12; x ^= x << 25; x ^= x >> 27;
    rng_state = x;
    return x * 0x2545F4914F6CDD1Dull;
}
/* signed coefficient in [-2^bits, 2^bits). */
static int32_t rng_coeff(unsigned bits) {
    uint32_t mask = (1u << (bits + 1u)) - 1u;
    int32_t v = (int32_t)(rng_next() & mask);
    return v - (int32_t)(1u << bits);
}

static const uint32_t kNs[3] = { 128u, 256u, 512u };
static const unsigned kBits[2] = { 23u, 28u };   /* medium, large(CRT-exercising) */

static int32_t a[512], b[512];
static int64_t e[512];

static void emit_i32(const char *name, const int32_t *v, uint32_t n) {
    printf("static const int32_t %s[%u] = {", name, n);
    for (uint32_t i = 0; i < n; i++) printf("%s%d,", (i % 12u == 0u) ? "\n    " : "", v[i]);
    printf("\n};\n");
}
static void emit_i64(const char *name, const int64_t *v, uint32_t n) {
    printf("static const int64_t %s[%u] = {", name, n);
    for (uint32_t i = 0; i < n; i++) printf("%s%lldll,", (i % 8u == 0u) ? "\n    " : "", (long long)v[i]);
    printf("\n};\n");
}

int main(void) {
    rng_seed(0xABCDEF0123456789ull);
    printf("/* AUTO-GENERATED by ntt_gen_fixture.c (gcc + __int128 oracle). DO NOT EDIT. */\n");
    printf("/* Cross-compiler parity fixture for T_NTT_3 (roadmap §3.7). M = %lld. */\n",
           (long long)SP_NTT_M);
    printf("#ifndef SP_NTT_REF_VECTORS_H\n#define SP_NTT_REF_VECTORS_H\n#include <stdint.h>\n\n");
    printf("typedef struct { uint32_t N; const int32_t *a; const int32_t *b; const int64_t *expected; } sp_ntt_ref_case_t;\n\n");

    int idx = 0;
    char nm[64];
    printf("/* case arrays */\n");
    int ncases = 0;
    /* first pass: emit arrays */
    for (int ni = 0; ni < 3; ni++) {
        for (int bi = 0; bi < 2; bi++) {
            uint32_t N = kNs[ni];
            for (uint32_t i = 0; i < N; i++) { a[i] = rng_coeff(kBits[bi]); b[i] = rng_coeff(kBits[bi]); }
            ntt_ref_negacyclic_mul(N, a, b, e);
            sprintf(nm, "c%d_a", idx); emit_i32(nm, a, N);
            sprintf(nm, "c%d_b", idx); emit_i32(nm, b, N);
            sprintf(nm, "c%d_e", idx); emit_i64(nm, e, N);
            idx++; ncases++;
        }
    }
    printf("\nstatic const sp_ntt_ref_case_t sp_ntt_ref_cases[] = {\n");
    for (int i = 0; i < ncases; i++)
        printf("    { %u, c%d_a, c%d_b, c%d_e },\n",
               kNs[(i / 2)], i, i, i);
    printf("};\n");
    printf("static const int sp_ntt_ref_ncases = %d;\n", ncases);
    printf("\n#endif /* SP_NTT_REF_VECTORS_H */\n");
    return 0;
}
