# sp_module.cmake — shared module helper for shannon-prime-system.
#
# Included by BOTH the root build (which add_subdirectory()'s every module)
# and by each module's standalone build (cmake -S core/<module>). It defines
# common flags, the SP_INCLUDE_DIR anchor, and the sp_add_module() helper that
# every core/<module>/CMakeLists.txt calls. Do not edit this file inside a
# Phase-1 module agent task — it is shared scaffold.

# The public header root is always <repo>/include, computed relative to THIS
# file regardless of who includes it.
get_filename_component(SP_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../include" ABSOLUTE)

option(SP_UBSAN "Enable UndefinedBehaviorSanitizer on SP targets" OFF)

# Resolve the UBSan flavour once. Linux gcc / clang ship libubsan and give
# rich diagnostics; MinGW-Builds gcc ships the instrumentation but NO runtime
# lib, so -fsanitize=undefined fails at link with "cannot find -lubsan".
# Detect that and fall back to trap-on-error, which needs no runtime and still
# aborts on any UB (sufficient for a "no UB" gate).
set(SP_UBSAN_C_OPT "")
set(SP_UBSAN_L_OPT "")
if(SP_UBSAN AND (CMAKE_C_COMPILER_ID MATCHES "GNU|Clang"))
    include(CheckLinkerFlag)
    check_linker_flag(C "-fsanitize=undefined" SP_HAVE_UBSAN_RT)
    if(SP_HAVE_UBSAN_RT)
        set(SP_UBSAN_C_OPT -fsanitize=undefined -fno-sanitize-recover=all)
        set(SP_UBSAN_L_OPT -fsanitize=undefined)
    else()
        message(STATUS "sp: libubsan not found; using -fsanitize-undefined-trap-on-error")
        set(SP_UBSAN_C_OPT -fsanitize=undefined -fsanitize-undefined-trap-on-error -fno-sanitize-recover=all)
        set(SP_UBSAN_L_OPT "")
    endif()
endif()

# Warning flags applied to every SP target. C11, warnings-as-signal.
set(SP_C_FLAGS "")
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    list(APPEND SP_C_FLAGS -Wall -Wextra -Wshadow -Wconversion -Wsign-conversion -Wpointer-arith)
elseif(MSVC)
    list(APPEND SP_C_FLAGS /W4)
endif()

# sp_add_module(<name>
#     SOURCES       <impl .c files>        # compiled into static lib sp_<name>
#     [TEST         <test .c>]             # one test executable test_<name>
#     [TEST_NAME    <ctest name>]          # default: T_<UPPER(name)>
#     [TEST_SOURCES <extra .c>]            # compiled into the test exe only
#                                          #   (e.g. parity oracles, fixtures)
# )
#
# Produces:
#   - static library  sp_<name>     (PUBLIC include dir = <repo>/include)
#   - executable       test_<name>  linking sp_<name>
#   - ctest entry      <TEST_NAME>   running test_<name>
function(sp_add_module name)
    cmake_parse_arguments(M "" "TEST;TEST_NAME" "SOURCES;TEST_SOURCES" ${ARGN})

    add_library(sp_${name} STATIC ${M_SOURCES})
    target_include_directories(sp_${name} PUBLIC ${SP_INCLUDE_DIR})
    target_compile_options(sp_${name} PRIVATE ${SP_C_FLAGS} ${SP_UBSAN_C_OPT})
    if(SP_UBSAN_L_OPT)
        target_link_options(sp_${name} PUBLIC ${SP_UBSAN_L_OPT})
    endif()

    if(M_TEST)
        if(NOT M_TEST_NAME)
            string(TOUPPER ${name} _u)
            set(M_TEST_NAME T_${_u})
        endif()
        add_executable(test_${name} ${M_TEST} ${M_TEST_SOURCES})
        target_link_libraries(test_${name} PRIVATE sp_${name})
        target_include_directories(test_${name} PRIVATE ${SP_INCLUDE_DIR})
        target_compile_options(test_${name} PRIVATE ${SP_C_FLAGS} ${SP_UBSAN_C_OPT})
        if(SP_UBSAN_L_OPT)
            target_link_options(test_${name} PRIVATE ${SP_UBSAN_L_OPT})
        endif()
        add_test(NAME ${M_TEST_NAME} COMMAND test_${name})
    endif()
endfunction()
